"""Description of your changes

Revision ID: c1797ad0d01c
Revises: d0c32b2f638c
Create Date: 2024-08-22 16:14:09.169993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1797ad0d01c'
down_revision: Union[str, None] = 'd0c32b2f638c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.drop_table('predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prediction', sa.REAL(), autoincrement=False, nullable=True)
    )
    op.create_table('evaluations',
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mse', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('rmse', sa.REAL(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
