"""Description of changes

Revision ID: d0c32b2f638c
Revises: 28e30cacd599
Create Date: 2024-08-22 13:44:28.017969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0c32b2f638c'
down_revision: Union[str, None] = '28e30cacd599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('evaluations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mse', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('rmse', sa.REAL(), autoincrement=False, nullable=True)
    )
    op.create_table('predictions',
    sa.Column('symbol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prediction', sa.REAL(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
